global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  # - job_name: 'otel'
  #   metrics_path: /v1/metrics
  #   static_configs:
  #     - targets: [ '0.0.0.0:55681' ]
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]